swagger: "2.0"
info:
  title: Room API
  version: 1.0.0
paths:
  /api/room/update:
    post:
      summary: Update room information
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Room update parameters
          required: true
          schema:
            $ref: '#/definitions/RoomUpdate'
      responses:
        '200':
          description: Successful update
          schema:
            $ref: '#/definitions/SuccessResponse'
        '400':
          description: Invalid request body
          schema:
            $ref: '#/definitions/ErrorResponse'
        '404':
          description: Room not found
          schema:
            $ref: '#/definitions/ErrorResponse'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorResponse'
definitions:
  RoomUpdate:
    type: object
    properties:
      room_id:
        type: string
        description: The ID of the room to be updated
      new_name:
        type: string
        description: The new name for the room
      add_member:
        type: array
        items:
          type: integer
        description: An array of user IDs to be added to the room
      remove_member:
        type: array
        items:
          type: integer
        description: An array of user IDs to be removed from the room

  SuccessResponse:
    type: object
    properties:
      status:
        type: integer
        example: 200
      message:
        type: string
        example: Update Room Info successfully
      data:
        type: object
        properties:
          doc:
            $ref: '#/definitions/Room'

  ErrorResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
