openapi: 3.0.0
info:
  title: Room API
  version: 1.0.0
paths:
  /api/room/update:
    post:
      summary: Update room information
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                room_id:
                  type: string
                  description: The ID of the room to be updated
                new_name:
                  type: string
                  description: The new name for the room
                add_member:
                  type: array
                  items:
                    type: integer
                  description: An array of user IDs to be added to the room
                remove_member:
                  type: array
                  items:
                    type: integer
                  description: An array of user IDs to be removed from the room
      responses:
        '200':
          description: Successful update
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: Update Room Info successfully
                  data:
                    type: object
                    properties:
                      doc:
                        $ref: '#/components/schemas/Room'
        '400':
          description: Invalid request body
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Room not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Room:
      type: object
      properties:
        // Define your Room schema here
        name:
          type: string
        creator:
          type: integer
        xcode:
          type: string
        room_type:
          type: string
        member:
          type: array
          items:
            type: integer
        is_deleted:
          type: boolean
          default: false
    Error:
      type: object
      properties:
        status:
          type: integer
        message:
          type: string
